// используется для того чтобы легче манипулировать монологм
let Quotes = [
    "I was there when body was bluer.",
    "Someone would call this website pure shit, but i prefer to call it my home",
    "It's only after we've lost everything that we're free to do anything.",
    "You might think i'm hardcoded, i'm not real and not alive, and you're right.",
    "My name is favicon.png. I would ask your name too, but you can't say anything.",
    "So what's now?",
    "Check lavacast.ru, the website of abstract jokes and pure surrealism.",
    "Please forget what i have said before, i'm running out from phrases.",
    "Freedom of word doesn't allow you to say any pervented shit",
    "Hello and welcome to my home",
    "Please forgive me for everything",
    "As once one master said: 'As once one master said:'",
    "Don't forget to drink about 50 liters of water a day",
    "keep yourself save",
    "i am a robot",
    "this is the best day of my life",
    "One day i will die but then i will be reborned and as cycle goes, say this shit",
    "i'm not a philosof, but that would be great",
    "Stop tapping me",
    "It would be nice to go walk with friends, today is amazing day, very sad i don't have friends, nor life.",
    "When i was yonger, i used to spin all time.",
    "Welcome",
    "I guess you like to tap me, how disturbing",
    "Stop tapping me and i will say you a secret (spoiler, i don't have any secrets)",
    "I know many languages: deutch, english, russian, spanish and more... As long as it supported by Google Translator",
    "Stop tapping me and go outside",
    "Isn't it funny? Just look at this. Everything",
    "press f12, copy everything from this website and start your own one",
    //`copy and paste this link into the search bar 'https://thespart.ru/flower' the password is ${passcode}`,
    "hah",
    "very sad i dont have any screamers for you",
    "you are brave enough to continue this monologue",
    "dont be a hero, stop this right now",
    "leave this website, it's not safe here",
    "one day we will meet in real life. this day would be a nightmare",
    "look at yourself, look what happened to you",
    "disgusting",
    "let me tell you a tale: there were ummovable rock. one human said: 'can you please move?', but rock ignored his request. So human murdered the rock and continued his journey. End",
    "if you will die in 10 seconds, what would you do?",
    "https://motherfuckingwebsite.com",
    "its kinda hard to imagine what could you possibly do, if you didn't tap me all this time",
    "AAAAAAAAAAAAAA oops sorry",
    "am i cure for you?",
    "but what if i could kill you?",
    "я не могу больше бухать",
    "HTTP ERROR. server returned status 418",
    "my other brothers are just digital copies of real cat named Sashka. ",
    "and everyone died",
    "eeeeeeEeeeeEeeeee",
    "all phrases leads to Quotes",
    "i was thinking about this all time",
    "in next life i will live happily",
    "you will probably rot in hell",
    "oh i understand now",
    "once i asked a bird: 'what i supposed to do with my life?' and then bird flew away. I still don't know what i should do seriously",
    "think outside the box",
    "right now i dont have enough logic to say something sentimental",
    "mindless shit",
    "i think this is my torture, being someone's logo and be here forever",
    "if life gives you lemons, you still need sugar to make lemonade",
    "forgive me",
    "life don't have a meaning so make your own one",
    "I remember a day i fall asleep and then my life changed forever. I started to see cats inside and outside and started to notice interesting pattern: there is no cat in catkind who could think in their own. Almost every cat shares same idea and follows same rules. However it doesn't make them look alike, they are actually pretty interesting. One can draw, one can write. But why cats even want to be identical to each other? Why don't they want to be creative and be themselves. Why they start to mimic each other and say stupid shit they dont want to say? Popularity. The worst thing catkind has. Popularity can turn you into a monster and ruin your life. It make you dizzy, stupid, and the worst of all `cool`. Being cool is not a problem, but being `cool` is. You must be `cool` so you start to do stupid things. You start to do what others say so you gain `status`. And i could say more... but then i woke up. And nothing changed",
    "Do not be fooled. Im not creator of this website and everything i say is not his words"
]

export default Quotes;